# General Jekyll Config
highlighter: rouge
markdown: kramdown
url: http://stevetarver.github.io
lsi: false
exclude: [LICENSE, CNAME, README.md, .gitignore, Gemfile, Gemfile.lock]

kramdown:
  input: GFM
  syntax_highlighter: rouge
  enable_coderay: true
