# General Jekyll Config
lsi: false
safe: true
markdown: kramdown
highlighter: rouge
url: http://stevetarver.github.io
exclude: [LICENSE, CNAME, README.md, .gitignore, Gemfile, Gemfile.lock]

kramdown:
  input: GFM
  highlighter: rouge
